name: Publish
on: [ workflow_dispatch ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Build and publish
        run: ./gradlew :versions:publishVersionsPublicationToGitHubPackagesRepository
